theme: jekyll-theme-cayman
title: <a href="https://ncar.github.io/CAM-chem/" style="color:#FFFFFF;"> Python resources for CAM-chem </a>
description: <a href="https://ncar.github.io/CAM-chem/" class="btn">Home</a> <a href="https://wiki.ucar.edu/display/camchem/Home" class="btn">CAM-chem Wiki</a>
github:
  is_project_page: false
