theme: jekyll-theme-cayman
title: <a href="https://ncar.github.io/CAM-chem/"> Python resources for CAM-chem </a>
description: <a href="https://ncar.github.io/CAM-chem/" class="btn">Home</a>
github:
  is_project_page: false
